### ISSUE TITLE
Re-write code crystal-build by Crystal

### ISSUE THREAD

**Issue by pine** [crenv/crystal-build#4]
I want to rewrite code crystal-build by Crystal.

**Comment by taylorthurlow** [comment]
For anyone interested in this, [I've started writing this](taylorthurlow/crystal-build-cr). Right now it just downloads prepackaged binaries from GitHub, and the platform it downloads for is hard-coded. You can probably make it work for you. Working on polishing it up and eventually actually building from scratch.

**Comment by pine** [comment]
Hi @taylorthurlow. I'm looking for maintainer.

Could you refer the issue if you have a free time? Thank you.

- https://github.com/pine/crenv/issues/47

**Comment by taylorthurlow** [comment]
Closing because the rewrite is largely functional and continued development effort will be put into this repository:

https://github.com/crenv/crystal-build-cr
