### ISSUE TITLE
Install 0.23.1 failed on Ubuntu 16.04 

### ISSUE THREAD

**Issue by david50407** [crenv/crystal-build#62]
Issue from https://github.com/pine/crenv/issues/35

When I'm installing Crystal 0.23.1 with crenv (https://github.com/pine/crenv/commit/7d55d72bc768eb263af2e1818b2ebfc3c65d3b9e) with crystal-build (https://github.com/pine/crystal-build/commit/77f9f5ed121e4c6af33a3dda13a869da4756f9f7), and failed on installing Shards (Error: Missing option: --link-flags).

Here's log:

```
~ > 2.2.1p85 > 0.22.0 > 6.10.3 > $ > crenv install 0.23.1
Resolving Crystal download URL by Remote Cache ... ng
Resolving Crystal download URL by GitHub ... ok
Downloading Crystal binary tarball ...
https://github.com/crystal-lang/crystal/releases/download/0.23.1/crystal-0.23.1-3-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   625    0   625    0     0    521      0 --:--:--  0:00:01 --:--:--   522
100 18.9M  100 18.9M    0     0  2002k      0  0:00:09  0:00:09 --:--:-- 3246k
ok
Moving the Crystal directory ...ok
Checking if Shards already exists ... ng
Resolving Shards download URL ... ok
Downloading Shards tarball ...
https://github.com/crystal-lang/shards/archive/master.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127    0   127    0     0     99      0 --:--:--  0:00:01 --:--:--    99
100 29763  100 29763    0     0  11304      0  0:00:02  0:00:02 --:--:-- 70195
ok
Building Shards ... Error: Missing option: --link-flags

Retry building Shards ... crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/home/davy/.crenv/versions/0.23.1/bin/crystal: line 102: 102819 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
shards build faild: /home/davy/.crenv/cache/0.23.1/shards-master at /home/davy/.crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Builder/Shards.pm line 33, <DATA> line 2.
```

**Comment by pine** [comment]
Hi. I'll check it.

Thank you.

**Comment by pine** [comment]
Now, crystal-build cache is old. I'll fix it tomorrow.

**Comment by pine** [comment]
Hi @david50407.

I update cache and fix crystal-build bugs, but I can't install Crystal v0.23.1 on Ubuntu.

It may be a bug in Crystal.
So, I'll support installing Shards binary.

If you are in a hurry, please try Crystal 0.23.0 🙇

Thank you.

**Comment by endorama** [comment]
Hello @pine @david50407, what you are currently experiencing is a bug in the LLVM and crystal.

You can follow it up here: [crystal-lang/crystal/issues/4719](https://github.com/crystal-lang/crystal/issues/4719)

I resolved downloading the prebuilt 0.24.1 binary and putting it in `$HOME/.anyenv/envs/crenv/versions/0.24.1`.

BTW, @pine I wasn't able to install `0.24.1` from `crenv` because was not in the `crenv install --list` output.

**Comment by pine** [comment]
> BTW, @pine I wasn't able to install 0.24.1 from crenv because was not in the crenv install --list output.

Hello @endorama.

I've updated crystal versions.
Could you confirm `crenv install --list` again?

Thank you.

**Comment by endorama** [comment]
@pine I created a new issue, as there are a couple of problems and I don't want to clutter this one! See #64

**Comment by pine** [comment]
Hi @david50407 @endorama. I'm looking for maintainer.

Could you refer the issue if you have a free time? Thank you.
